"""
LLM Service for Factual-ai
===========================
This module handles communication with the available DeepSeek-V3 LLM endpoint hosted 
on TCS GenAILab. It provides standard chat completions and structured JSON generations,
using the standard openai SDK and an HTTP client with SSL verification disabled to 
ensure seamless connection.
"""

import os
import httpx
from openai import OpenAI

class LLMService:
    """
    Service wrapper for DeepSeek-V3 hosted on TCS GenAILab.
    """

    def __init__(self):
        # Configure client to bypass SSL verify as specified in the reference image
        self.http_client = httpx.Client(verify=False)
        
        # Read API key, base URL, and model from environment variables, fallback to defaults
        self.base_url = os.getenv("LLM_BASE_URL", "https://genailab.tcs.in")
        self.api_key = os.getenv("LLM_API_KEY", "sk-h4SzToxOqOneSAXq191PXA")
        self.model = os.getenv("LLM_MODEL", "azure_ai/genailab-maas-DeepSeek-V3-0324")

        # Initialize the OpenAI client pointing to the GenAILab Proxy
        self.client = OpenAI(
            base_url=self.base_url,
            api_key=self.api_key,
            http_client=self.http_client
        )

    def ask(self, prompt: str) -> str:
        """
        Executes a standard chat completion request using DeepSeek-V3.
        
        Args:
            prompt: The string prompt containing user input and rules.
            
        Returns:
            The raw text content generated by the model.
        """
        response = self.client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2
        )
        return response.choices[0].message.content.strip()

    def ask_json(self, prompt: str) -> str:
        """
        Executes a chat completion requesting a structured JSON response.
        
        Args:
            prompt: The string prompt instructing the model to return valid JSON.
            
        Returns:
            A string containing the raw JSON output.
        """
        response = self.client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"},
            temperature=0.0
        )
        return response.choices[0].message.content.strip()
