@echo off
echo Setting up path for OpenSSL...
set "PATH=%PATH%;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin"
echo Running @adobe/ccweb-add-on-ssl setup...
npx @adobe/ccweb-add-on-ssl setup --hostname localhost
